@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '2.0.0'
String imgTag  = "v" + version

olcnePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/ui-plugins:' + imgTag): 'olcne/ui-plugins:' + imgTag],
        platforms: ['ol8'],
        architectures: ['x86_64', 'aarch64'],
        publishImage: false,
        yumOL8Repos: ['ol8_appstream'],
        ol8ModulesToEnable: ['nodejs:20'],
)
